pools:
  - id: HTTP pool
    gun:
      type: gprc_gun   # custom gun name (specified at `register.Gun("my_custom_gun_name", ...`)
      target: "localhost:84"
    ammo:
      type: custom_provider
      source:
        type: file
        path: json.ammo
    result:
      type: phout
      destination: ./phout.log
    rps: { duration: 10s, type: line,  from: 400, to: 1000 }
    startup:
      type: once
      times: 10

log:                                 # gun logging configuration
  level: error                       # log only `error` messages (`debug` for verbose logging)

monitoring:
  expvar:                            # gun statistics HTTP server
    enabled: true
    port: 1234
  cpuprofile:                        # cpu profiling
    enabled: true
    file: "cpuprofile.log"
  memprofile:                        # mem profiling
    enabled: true
    file: "memprofile.log"