// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sample

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SaveResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSaveResponse(buf []byte, offset flatbuffers.UOffsetT) *SaveResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SaveResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSaveResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSaveResponse(buf []byte, offset flatbuffers.UOffsetT) *SaveResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SaveResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSaveResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SaveResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SaveResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SaveResponse) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SaveResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SaveResponseAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(message), 0)
}
func SaveResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
