global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: json-docs-service
    metrics_path: /metrics
    static_configs:
      - targets: ['json-docs-service:9091']