// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sample

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Goods struct {
	_tab flatbuffers.Table
}

func GetRootAsGoods(buf []byte, offset flatbuffers.UOffsetT) *Goods {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Goods{}
	x.Init(buf, n+offset)
	return x
}

func FinishGoodsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGoods(buf []byte, offset flatbuffers.UOffsetT) *Goods {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Goods{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGoodsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Goods) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Goods) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Goods) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Goods) Amount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Goods) MutateAmount(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *Goods) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GoodsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GoodsAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func GoodsAddAmount(builder *flatbuffers.Builder, amount int32) {
	builder.PrependInt32Slot(1, amount, 0)
}
func GoodsAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(code), 0)
}
func GoodsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
