// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sample

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SaveRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSaveRequest(buf []byte, offset flatbuffers.UOffsetT) *SaveRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SaveRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSaveRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSaveRequest(buf []byte, offset flatbuffers.UOffsetT) *SaveRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SaveRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSaveRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SaveRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SaveRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SaveRequest) Document(obj *Document) *Document {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Document)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SaveRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SaveRequestAddDocument(builder *flatbuffers.Builder, document flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(document), 0)
}
func SaveRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
