// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package sample

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ValidateResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsValidateResponse(buf []byte, offset flatbuffers.UOffsetT) *ValidateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ValidateResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishValidateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsValidateResponse(buf []byte, offset flatbuffers.UOffsetT) *ValidateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ValidateResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedValidateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ValidateResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ValidateResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ValidateResponse) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ValidateResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ValidateResponseAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(message), 0)
}
func ValidateResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
